/* Coastal Almanac itineraries: an interactive route editor that helps visitors choose a pace without turning Mangaluru into a checklist. */
import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, CalendarDays, Clock3, Sun } from "lucide-react";
import { Link } from "wouter";
import { IMG } from "@/data/siteData";

const routes = [
  { id: "first", label: "First time, one day", title: "A first taste of the coast.", copy: "Breakfast, a city story, and a west-facing final hour. Enough structure to settle in, enough air to notice what else is there.", image: IMG.panambur, stops: [["08:30", "Breakfast while the city wakes"], ["11:30", "A heritage pause"], ["17:00", "Panambur in the long light"]], note: "Best for: an uncomplicated first meeting." },
  { id: "slow", label: "A slow weekend", title: "Two days with room around them.", copy: "Let day one belong to the coast and day two move through the city’s markets, old rooms, and generous tables.", image: IMG.port, stops: [["Day 1", "Coast, lunch, late light"], ["Day 2", "Market, temple, dinner"], ["Either day", "Leave one hour unclaimed"]], note: "Best for: lingering without a long list." },
  { id: "food", label: "A food-led day", title: "Let appetite keep the time.", copy: "Make breakfast the anchor, let the market choose lunch, and end where a table is willing to keep you a little longer.", image: IMG.food, stops: [["08:00", "Neer dosa and coffee"], ["13:00", "A market-led lunch"], ["20:00", "A dinner worth taking slowly"]], note: "Best for: a traveller with a very good appetite." },
];

export default function Itineraries() {
  const [active, setActive] = useState("first");
  const route = useMemo(() => routes.find((item) => item.id === active) ?? routes[0], [active]);
  return <>
    <section className="itinerary-hero"><motion.div initial={{ opacity: 0, x: -24 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .7 }} className="itinerary-hero-copy"><span className="almanac-overline">Not every good day needs a timetable</span><h1>Find the<br />right <em>rhythm.</em></h1><p>These are loose patterns, not instructions. Use them to begin, then make room for weather, appetite, and an unexpectedly good turn.</p><div><span><CalendarDays size={14} /> One day to a long weekend</span><span><Clock3 size={14} /> Made to be reshaped</span></div></motion.div><motion.img initial={{ clipPath: "inset(0 0 0 100%)" }} animate={{ clipPath: "inset(0 0 0 0)" }} transition={{ duration: .85, ease: [0.77, 0, .175, 1] }} src={IMG.church} alt="Historic church in Mangaluru" /></section>
    <section className="section-shell itinerary-editor"><div className="itinerary-editor-head"><span className="almanac-label">Choose a way in</span><h2>What should the<br />weekend <em>feel like?</em></h2></div><div className="itinerary-editor-layout"><div className="itinerary-route-switch">{routes.map((item, index) => <button key={item.id} className={active === item.id ? "active" : ""} onClick={() => setActive(item.id)}><span>0{index + 1}</span><strong>{item.label}</strong><ArrowRight size={15} /></button>)}</div><AnimatePresence mode="wait"><motion.article key={route.id} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -18 }} transition={{ duration: .35 }} className="itinerary-route-detail"><img src={route.image} alt={route.title} /><div className="itinerary-route-shade" /><div className="itinerary-route-content"><span>{route.note}</span><h3>{route.title}</h3><p>{route.copy}</p><ol>{route.stops.map(([time, stop]) => <li key={time}><b>{time}</b><span>{stop}</span></li>)}</ol><Link href="/plan-your-visit" className="almanac-button light">Personalise this day <ArrowRight size={16} /></Link></div></motion.article></AnimatePresence></div></section>
    <section className="itinerary-break"><div className="section-shell"><div className="itinerary-break-title"><span className="almanac-label">A useful break in the middle</span><h2>Do less at<br /><em>2:30 pm.</em></h2></div><div className="itinerary-break-copy"><Sun size={22} /><p>That is not a missing piece of the itinerary. It is the point. Find shade, order something cold, and let the city become less deliberate for a while.</p><Link href="/food" className="almanac-text-action">A food-led afternoon <ArrowRight size={15} /></Link></div></div></section>
    <section className="section-shell itinerary-grid-section"><div className="itinerary-grid-head"><span className="almanac-label">Three small rules</span><h2>Build the day<br />with <em>better gaps.</em></h2></div><div className="itinerary-rule-grid"><article><span>01</span><h3>One anchor</h3><p>Choose the place that matters most, then let everything else orbit it.</p></article><article><span>02</span><h3>One meal</h3><p>Do not just fit food between attractions. Let it become one of the reasons you came.</p></article><article><span>03</span><h3>One empty hour</h3><p>The city’s best details live in the time you did not completely allocate.</p></article></div></section>
    <section className="itinerary-close"><div className="section-shell"><span className="almanac-label">Ready to make this yours?</span><h2>The best trip has<br />a little <em>weather</em> in it.</h2><p>Tell us your pace, your time, and what you hope to feel. We will sketch a day with enough space to become your own.</p><Link href="/plan-your-visit" className="almanac-button primary">Shape my visit <ArrowRight size={16} /></Link></div></section>
  </>;
}
